### ISSUE TITLE
Too Many Transactions

### ISSUE THREAD

**Issue by argonmining** [coderofstuff/kaspa-transaction-report#1]
Identified an issue with one of my wallets I use for mining. When i use the webapp in production I get the loading screen for a moment and then nothing. The screen shows as if it has reloaded but doesn't show a link for report download. 

Upon inspection in Chrome dev tools, it looks like the error is in the following API call

Request URL:
https://api.kaspa.org/transactions/search
Request Method:
POST

That API call receives a response of "{"detail":"Too many transaction ids"}"

Can anything be done to paginate this API call when wallets show transaction counts above the threshold for that api endpoint?

**Comment by coderofstuff** [comment]
Thanks for reporting @awood0540. Looking at the rest api, there is indeed a limit for the number transaction IDs that can be passed at a time (1000): https://github.com/lAmeR1/kaspa-rest-server/blob/40fdccd3d00bfef043b987a1098f201b7669577c/endpoints/get_transactions.py#L176

So I'll request over these transaction Ids in groups of 1000 or less.

**Comment by argonmining** [comment]
Thanks so much @coderofstuff !! I really appreciate all of your effort, time, and contributions to the kaspa community!

**Comment by tchey290** [comment]
> Thanks for reporting @awood0540. Looking at the rest api, there is indeed a limit for the number transaction IDs that can be passed at a time (1000): https://github.com/lAmeR1/kaspa-rest-server/blob/40fdccd3d00bfef043b987a1098f201b7669577c/endpoints/get_transactions.py#L176
> 
> So I'll request over these transaction Ids in groups of 1000 or less.

Hi, have you implemented this fix? I am still getting the too many transactions error

**Comment by coderofstuff** [comment]
Should be fixed in 818de3a5172a6113abc5172f4910191b8adf7b87

Try it @awood0540 @tchey290
